# Generated by Django 5.2.11 on 2026-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('call_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FinalExamInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateField(auto_now_add=True)),
                ('final_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_inscriptions', to='enrollments.finalexam')),
            ],
        ),
    ]
