# Generated by Django 5.2.11 on 2026-02-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalexaminscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_inscriptions', to='users.student'),
        ),
        migrations.AddField(
            model_name='subjectinscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_inscriptions', to='users.student'),
        ),
        migrations.AddField(
            model_name='subjectinscription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_inscriptions', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='finalexaminscription',
            index=models.Index(fields=['student'], name='enrollments_student_caf777_idx'),
        ),
        migrations.AddIndex(
            model_name='finalexaminscription',
            index=models.Index(fields=['final_exam'], name='enrollments_final_e_e077ab_idx'),
        ),
        migrations.AddIndex(
            model_name='finalexaminscription',
            index=models.Index(fields=['inscription_date'], name='enrollments_inscrip_128d44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finalexaminscription',
            unique_together={('student', 'final_exam')},
        ),
        migrations.AddIndex(
            model_name='subjectinscription',
            index=models.Index(fields=['student'], name='enrollments_student_d7de90_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectinscription',
            index=models.Index(fields=['subject'], name='enrollments_subject_c551d5_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectinscription',
            index=models.Index(fields=['inscription_date'], name='enrollments_inscrip_4253a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectinscription',
            unique_together={('student', 'subject')},
        ),
    ]
