# Generated by Django 5.2.11 on 2026-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('grading', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject'], name='grading_gra_student_5a9156_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['status'], name='grading_gra_status_61e56c_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'status'], name='grading_gra_student_2e79d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject')},
        ),
    ]
