# Generated by Django 5.2.11 on 2026-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('dean', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=100)),
                ('duration_years', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='academics.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('obligatory', 'Obligatory'), ('elective', 'Elective')], max_length=10)),
                ('period', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('annual', 'Annual')], max_length=10)),
                ('semanal_hours', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.career')),
            ],
        ),
    ]
